approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmScopes:
  ai-soft-jp:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com"
